### ISSUE TITLE
TypeError on every CLI call

### ISSUE THREAD

**Issue by alexdetsch** [ephes/kptncook#18]
Regardless of which CLI-command is called, everytime, this exact error is raised:
```
Traceback (most recent call last):
  File "/root/.local/bin/kptncook", line 5, in <module>
    from kptncook import cli
  File "/root/.local/pipx/venvs/kptncook/lib/python3.9/site-packages/kptncook/__init__.py", line 15, in <module>
    from .api import KptnCookClient, parse_id
  File "/root/.local/pipx/venvs/kptncook/lib/python3.9/site-packages/kptncook/api.py", line 120, in <module>
    def parse_id(text: str) -> tuple[Literal["oid", "uid"], str] | None:
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'
```
I use Python 3.9.2

**Comment by alexdetsch** [comment]
Ok, found out, that it needs at least python 3.10. It works now, I'll add a PR that mention this requirement to the README

**Comment by ephes** [comment]
Thanks for reporting this. Adding this to the README would be really helpful.

In the pyproject.toml is stated python >= 3.9 is required which is wrong, I'll just fix that.
