### ISSUE TITLE
PydanticImportError

### ISSUE THREAD

**Issue by maxboettinger** [ephes/kptncook#24]
Hi Jochen,

whilst trying to run your awesome package I came across a breaking error, probably because of a new dependency version of pydantic.
I found this happening in a clean anaconda environment for both python 3.10 and 3.11 when running any command.

This is the error I get:

`
Traceback (most recent call last):
  File "/Users/max/.local/bin/kptncook", line 5, in <module>
    from kptncook import cli
  File "/Users/max/.local/pipx/venvs/kptncook/lib/python3.11/site-packages/kptncook/__init__.py", line 16, in <module>
    from .api import KptnCookClient, parse_id
  File "/Users/max/.local/pipx/venvs/kptncook/lib/python3.11/site-packages/kptncook/api.py", line 8, in <module>
    from .config import settings
  File "/Users/max/.local/pipx/venvs/kptncook/lib/python3.11/site-packages/kptncook/config.py", line 7, in <module>
    from pydantic import (
  File "/Users/max/.local/pipx/venvs/kptncook/lib/python3.11/site-packages/pydantic/__init__.py", line 218, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/max/.local/pipx/venvs/kptncook/lib/python3.11/site-packages/pydantic/_migration.py", line 294, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: BaseSettings has been moved to the pydantic-settings package. See https://docs.pydantic.dev/2.4/migration/#basesettings-has-moved-to-pydantic-settings for more details.
For further information visit https://errors.pydantic.dev/2.4/u/import-error
`

I would really appreciate you looking into this.

Thanks in advance! :)

**Comment by ephes** [comment]
Should be fixed by now.
